# ios/Podfile

# React-Native 스크립트 로딩
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage
  use_frameworks! :linkage => linkage.to_sym
end

target 'credittalk' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
end

post_install do |installer|
  react_native_post_install(installer)

  installer.pods_project.targets.each do |target|
    if target.name.start_with?('React') || target.name == 'kakao-login'
      target.build_configurations.each do |config|
        config.build_settings['DEFINES_MODULE']                                    = 'YES'
        config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
      end
    end
  end
end
