CREATE TABLE IF NOT EXISTS "public"."banned_phones" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "phone_number" text NOT NULL,
    "banned_by" uuid NOT NULL,
    "banned_user_id" uuid,
    "reason" text
);

ALTER TABLE ONLY "public"."banned_phones"
    ADD CONSTRAINT "banned_phones_phone_number_key" UNIQUE ("phone_number");

ALTER TABLE ONLY "public"."banned_phones"
    ADD CONSTRAINT "banned_phones_banned_by_fkey"
    FOREIGN KEY ("banned_by") REFERENCES "public"."users"("auth_user_id") ON DELETE SET NULL;

ALTER TABLE ONLY "public"."banned_phones"
    ADD CONSTRAINT "banned_phones_banned_user_id_fkey"
    FOREIGN KEY ("banned_user_id") REFERENCES "public"."users"("auth_user_id") ON DELETE SET NULL;

ALTER TABLE "public"."banned_phones" ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE "public"."banned_phones" TO "anon";
GRANT ALL ON TABLE "public"."banned_phones" TO "authenticated";
GRANT ALL ON TABLE "public"."banned_phones" TO "service_role";
